version: '3.8'

services:
  mongodb:    
    image: mongo:latest    
    container_name: mongodb    
    ports:      
      - "31017:27017"    
    environment:      
      MONGO_INITDB_ROOT_USERNAME: root      
      MONGO_INITDB_ROOT_PASSWORD: example    
    volumes:      
      - ./data/db:/data/db    
    networks:      
      - network-mongo    
    hostname: mongodb    
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:      
      driver: "json-file"      
      options:        
        max-size: "10m"        
        max-file: "3"  

  mongo-express:    
    depends_on:      
      - mongodb    
    image: mongo-express:latest    
    container_name: mongo-express    
    ports:      
      - "31081:8081"    
    environment:      
      ME_CONFIG_MONGODB_PORT: 27017      
      ME_CONFIG_MONGODB_SERVER: mongodb      
      ME_CONFIG_MONGODB_ADMINUSERNAME: root      
      ME_CONFIG_MONGODB_ADMINPASSWORD: example      
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/    
    networks:      
      - network-mongo    
    hostname: mongo-express    
    entrypoint: ["sh", "-c", "until nc -z mongodb 27017; do echo Waiting for mongodb:27017...; sleep 2; done; npm start"]
    restart: always

networks:  
  network-mongo:    
    driver: bridge
